spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OrderSystem?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
    #        show_sql: true ?? ?? SQL ?? ??
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.example.file_test: debug

springdoc:
  packages-to-scan: com.gio.ordersystem
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  api-docs:
    path: /api
  cache:
    disabled: true

  swagger-ui:
    path: /ui
    operations-sorter: method
    display-request-duration: true # ??? ?? ??? UI?? ??
    persist-authorization: true # ?? ??? ????? ??
    deep-linking: true # URL ??? ?? API ?? ???? ???
    doc-expansion: list # ?? ?? ?? ??: ??? ?? (?? none, full ??)