version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql-container'
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'       # 루트 계정 암호
      - 'MYSQL_DATABASE=OrderSystem'    # 기본 데이터베이스
    ports:
      - '3306:3306'                      # 기본 DB를 위한 포트

  # 테스트용 MySQL 설정
  mysql-test:
    image: 'mysql:latest'
    container_name: 'mysql-test-container'
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'       # 루트 계정 암호
      - 'MYSQL_DATABASE=OrderSystemTest' # 테스트 데이터베이스
    ports:
      - '3307:3306'                      # 테스트 DB를 위한 포트


  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter
    command:
      - "--mysqld.username=root:1234"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"                       # MySQL Exporter 포트
    depends_on:
      - mysql