version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=row
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: OrderSystem
    ports:
      - 3306:3306

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    depends_on:
      - mysql-master
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --relay-log=mysql-relay-bin
      --log-slave-updates=1
      --read-only=1
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: OrderSystem
    ports:
      - 3307:3306

  mysql-master-exporter:
    container_name: mysql-master-exporter
    image: prom/mysqld-exporter:latest
    restart: always
    command:
      - "--mysqld.address=mysql-master:3306"
      - "--mysqld.username=root:1234"
    ports:
      - "9104:9104"
    depends_on:
      - mysql-master

  mysql-slave-exporter:
    container_name: mysql-slave-exporter
    image: prom/mysqld-exporter:latest
    restart: always
    command:
      - "--mysqld.address=mysql-slave:3306"
      - "--mysqld.username=root:1234"
    ports:
      - "9105:9104"
    depends_on:
      - mysql-slave

  redis-master:
    image: 'redis:latest'
    container_name: 'redis-master'
    ports:
      - '6379:6379'
    command: redis-server --appendonly no
    # Master Redis 설정

  redis-slave:
    image: 'redis:latest'
    container_name: 'redis-slave'
    depends_on:
      - redis-master
    ports:
      - '6380:6379'
    command: >
      redis-server --replicaof redis-master 6379 --appendonly no
    # Slave Redis 설정 (Master 복제)

  redis-master-exporter:
    image: 'oliver006/redis_exporter:latest'
    container_name: 'redis-master-exporter'
    environment:
      - REDIS_ADDR=redis-master:6379
    ports:
      - '9121:9121'
    depends_on:
      - redis-master

  redis-slave-exporter:
    image: 'oliver006/redis_exporter:latest'
    container_name: 'redis-slave-exporter'
    environment:
      - REDIS_ADDR=redis-slave:6379
    ports:
      - '9122:9121'
    depends_on:
      - redis-slave

networks:
  default:
    driver: bridge
