version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=row
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: OrderSystem
    ports:
      - 3306:3306

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    depends_on:
      - mysql-master
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --relay-log=mysql-relay-bin
      --log-slave-updates=1
      --read-only=1
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: OrderSystem
    ports:
      - 3307:3306

  mysql-master-exporter:
    container_name: mysql-master-exporter
    image: prom/mysqld-exporter:latest
    restart: always
    command:
      - "--mysqld.address=mysql-master:3306"
      - "--mysqld.username=root:1234"
    ports:
      - "9104:9104"
    depends_on:
      - mysql-master

  mysql-slave-exporter:
    container_name: mysql-slave-exporter
    image: prom/mysqld-exporter:latest
    restart: always
    command:
      - "--mysqld.address=mysql-slave:3306"
      - "--mysqld.username=root:1234"
    ports:
      - "9105:9104"
    depends_on:
      - mysql-slave
